### ISSUE TITLE
schema generation panics

### ISSUE THREAD

**Issue by heiko-braun** [loft-sh/vcluster-values#18]
When trying to generate the schema, it fails on the `s.Properties` part:

```
GOWORK=off go run -mod vendor hack/schema/main.go     
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10297e7e0]

goroutine 1 [running]:
github.com/wk8/go-ordered-map/v2.(*OrderedMap[...]).Get(...)
	/Users/hbraun/dev/prj/vcluster-values/vendor/github.com/wk8/go-ordered-map/v2/orderedmap.go:93
main.transformMapProperties(0x14000150b08)
	/Users/hbraun/dev/prj/vcluster-values/hack/schema/main.go:78 +0x20
main.main()
	/Users/hbraun/dev/prj/vcluster-values/hack/schema/main.go:21 +0x50
exit status 2
```

**Comment by heiko-braun** [comment]
Fixed with #19
